### ISSUE TITLE
Implement YAGNI ("You Aren't Gonna Need It")  Principle

### ISSUE THREAD

**Issue by azrielpamungkas** [pahleviii1705/siamawolu-fe#1]
Bagaimana kalau membuat branch khusus untuk development? jadi tidak semua assets / code di satu branch

**Comment by aydinpramasta** [comment]
jadi di branch main hanya codingan page frontend yang sudah fix?

**Comment by azrielpamungkas** [comment]
Yang sudah fix and on going code @aydinpramasta

**Comment by azrielpamungkas** [comment]
mungkin struktur branchnya seperti ini Sir,
-- Main
-- Dist (Suggest Name)

Atau Tetep di branch main, tapi template defaultnya di masukin di folder Dist

**Comment by aydinpramasta** [comment]
boleh dicoba, gimana pendapat @ujklm23 @Sinduaditya @iqbalika @Mouna655

**Comment by Sinduaditya** [comment]
Menurut Saya  Boleh Boleh saja pak🙏🏻

**Comment by Sinduaditya** [comment]
Pak saya izin ke toilet🙏🏻🙏🏻🙏🏻

**Comment by Sinduaditya** [comment]
> Yang sudah fix and on going code@aydinpramasta

SIAP KAK
